### ISSUE TITLE
Pixel-based Regression

### ISSUE THREAD

**Issue by TolgaBkm** [MIC-DKFZ/image_classification#1]
Hello!
Is it possible to perform pixel-based regression with your library?
There is a poster regression example, however it assigns one value for the whole image. I'm looking for to assign a regressive value for each pixel in the image.

**Comment by seziegler** [comment]
Hi @TolgaBkm ,

unfortunately this is not possible with the library because this library covers image-level labels only (either a classification label or a regression target). Your use case sounds more like a segmentation problem but with regression values instead of pixel-level classes. This is actually planned to be available in the next version of [nnunet](https://github.com/MIC-DKFZ/nnUNet), so you can have a look there in the future! 

Best,
Sebastian

**Comment by TolgaBkm** [comment]
Thank you for your reply!
